// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIuYejvMdVgHb12f7vhoAQ8OV-a1Rk4GE',
    appId: '1:46942427883:android:b28dc85192fa6ca74afcae',
    messagingSenderId: '46942427883',
    projectId: 'jisestates',
    storageBucket: 'jisestates.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUEYbfaz6yf-WTtCCYZPR52i5tRXb72yw',
    appId: '1:46942427883:ios:c1a59d5c873471a24afcae',
    messagingSenderId: '46942427883',
    projectId: 'jisestates',
    storageBucket: 'jisestates.appspot.com',
    iosBundleId: 'com.pj.tmk.nkog.housingInformationWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUEYbfaz6yf-WTtCCYZPR52i5tRXb72yw',
    appId: '1:46942427883:ios:c1a59d5c873471a24afcae',
    messagingSenderId: '46942427883',
    projectId: 'jisestates',
    storageBucket: 'jisestates.appspot.com',
    iosBundleId: 'com.pj.tmk.nkog.housingInformationWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKcmNqBMbng6008DLcYh9FAZ1GUHGwyF8',
    appId: '1:46942427883:web:2cc544c25af6c3064afcae',
    messagingSenderId: '46942427883',
    projectId: 'jisestates',
    authDomain: 'jisestates.firebaseapp.com',
    storageBucket: 'jisestates.appspot.com',
    measurementId: 'G-72SCH2354M',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKcmNqBMbng6008DLcYh9FAZ1GUHGwyF8',
    appId: '1:46942427883:web:2cc544c25af6c3064afcae',
    messagingSenderId: '46942427883',
    projectId: 'jisestates',
    authDomain: 'jisestates.firebaseapp.com',
    storageBucket: 'jisestates.appspot.com',
    measurementId: 'G-72SCH2354M',
  );

}